version: '3'
services:
  mariabd:
    image: mariadb
    container_name: 'nest-todo-mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
    hostname: '127.0.0.1'
    ports:
      - '3306:3306'
  redis:
    image: redis
    container_name: 'nest-todo-redis'
    hostname: '127.0.0.1'
    ports:
      - '6379:6379'
